### PR TITLE
merge to master

### PR DESCRIPTION
**Pull request by jackli0855**

### CODE REVIEW

**Comment by ThetOo** [comment]
Can you see website?
Because client claim to me.

**Comment by jackli0855** [comment]
to Oosan

I cannot see
do you know the reason?

from libao

2015-01-31 21:47 GMT+08:00 ThetOo notifications@github.com:

> Can you see website?
> Because client claim to me.

**Comment by jackli0855** [comment]
to Oosan
I have started web server urgently

from libao

2015-02-01 14:27 GMT+08:00 Bao Li libaohoo@gmail.com:

> to Oosan
> 
> I cannot see
> do you know the reason?
> 
> from libao
> 
> 2015-01-31 21:47 GMT+08:00 ThetOo notifications@github.com:
> 
> > Can you see website?
> > Because client claim to me.

**Comment by ThetOo** [comment]
Really?
How should we do it?

**Comment by ThetOo** [comment]
Did you solved it.
Now i can see website.
How did you do?

**Pull request merged**
